### ISSUE TITLE
ipcamera does not load

### ISSUE THREAD

**Issue by aurelio1** [Skinah/IpCamera#25]
I have downloaded the latest ipcamera binding (version 2016-02-16) to the addins folder and unzipped it. However, oh2 fails to load. The messages are:
```
2019-02-24 23:56:54.350 [DEBUG] [org.openhab.binding.ipcamera        ] - BundleEvent INSTALLED - org.openhab.binding.ipcamera
2019-02-24 23:56:54.839 [DEBUG] [org.openhab.binding.ipcamera        ] - BundleEvent RESOLVED - org.openhab.binding.ipcamera
2019-02-24 23:56:54.847 [DEBUG] [org.openhab.binding.ipcamera        ] - BundleEvent [unknown:512] - org.openhab.binding.ipcamera
2019-02-24 23:56:54.879 [DEBUG] [org.openhab.binding.ipcamera        ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=486, service.bundleid=252, service.scope=bundle, component.name=org.openhab.binding.ipcamera.internal.IpCameraHandlerFactory, component.id=289} - org.openhab.binding.ipcamera
2019-02-24 23:56:54.897 [DEBUG] [org.openhab.binding.ipcamera        ] - BundleEvent STARTING - org.openhab.binding.ipcamera
2019-02-24 23:56:54.911 [DEBUG] [org.openhab.binding.ipcamera        ] - BundleEvent STARTED - org.openhab.binding.ipcamera
2019-02-24 23:57:05.158 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-ipcamera'

```
Any idea?

**Comment by Skinah** [comment]
Have you done a cache and tmp folder cleanup? What version of Openhab?

**Comment by aurelio1** [comment]
tried a cleanup of both cache and tmp, but without success. However I got the following messages on the console (not on the openhab logs):
```
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
        Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.eclipse.smarthome.io.rest.sse.
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1005)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1025)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:964)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: org.osgi.framework.BundleException: Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.eclipse.smarthome.io.rest.sse.
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
                at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
                at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
                at org.eclipse.osgi.container.Module.doStart(Module.java:581)
                at org.eclipse.osgi.container.Module.start(Module.java:449)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
                at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161)
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1116)
                at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997)
                ... 6 more
        Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.media.sse.SseFeature
                at org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start(SseActivator.java:49)
                at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
                at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
                ... 16 more

```
Can that help?

**Comment by aurelio1** [comment]
and my openhab version is 2.5.0~S1512-1

**Comment by aurelio1** [comment]
With openHAB 2.5.0 Build #1538 and yesterday's ipcamera build same problem.

**Comment by Skinah** [comment]
Is that a snapshot build of openhab? If so the snapshots are very buggy since they
Started removing the eclipse smart home framework. Only use the milestone 1 for 2.5 or stick to openhab 2.4 stable.

Never seen that happen before but a similar message has been coming up for other bindings and deleting the addons.config file solves it for me as you can get conflicts with a second file addons.cfg

**Comment by aurelio1** [comment]
Thank you for your feedback. Removing addons.config did not change anything, but switching back to 2.4 stable did it. I should have expected that using a snapshot might result in problems like this - sorry for bothering you. Now I will proceed to configuring ipcamera :-)
