### ISSUE TITLE
empty password is causing an NPE 

### ISSUE THREAD

**Issue by Joachim2709** [Skinah/IpCamera#27]
2019-06-07 08:45:05.319 [WARN ] [pcamera.internal.StreamServerHandler] - Exception caught from stream server:{}

java.lang.NullPointerException: null

	at org.openhab.binding.ipcamera.handler.IpCameraHandler.setupFfmpegFormat(IpCameraHandler.java:475) ~[?:?]

	at org.openhab.binding.ipcamera.internal.StreamServerHandler.channelRead(StreamServerHandler.java:77) ~[?:?]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [227:io.netty.transport:4.1.34.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [222:io.netty.codec:4.1.34.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [222:io.netty.codec:4.1.34.Final]

	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [227:io.netty.transport:4.1.34.Final]

	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [224:io.netty.handler:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [227:io.netty.transport:4.1.34.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [227:io.netty.transport:4.1.34.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [225:io.netty.common:4.1.34.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [225:io.netty.common:4.1.34.Final]

	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by Skinah** [comment]
Thanks for reporting, I am testing some changes now which will solve this in the next build.

**Comment by Skinah** [comment]
new build is out, can you test it? as none of my cameras allow no passwords and it wont be for 3 weeks at least before I have a camera that can be used to test for this.

**Comment by Joachim2709** [comment]
Is working now! Thanks
