### ISSUE TITLE
Camera remains offline and pan & tilt work intermittently 

### ISSUE THREAD

**Issue by brootes** [Skinah/IpCamera#4]
I am working with a FOSCAM FI9821PR. The updateImageNow, imageurl and image channels seem to work fine. The camera will show OFFLINE - Configuration_Pending but still work for these channels.

The Pan and Tilt seem to work intermittently. I am getting the following error:

018-05-16 16:57:41.545 [vent.ItemStateChangedEvent] - FF_Office_Camera_Tilt changed from 35 to 49
==> /var/log/openhab2/openhab.log <==
2018-05-16 16:57:41.627 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0008: Bad Response; null
2018-05-16 16:57:41.639 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.ipcamera.handler.IpCameraHandler@fdedb4': No profile available for token: prof1
java.lang.IllegalArgumentException: No profile available for token: prof1
	at de.onvif.soap.devices.PtzDevices.getPTZConfiguration(PtzDevices.java:70) [239:org.openhab.binding.ipcamera:2.3.0.201805130058]
	at de.onvif.soap.devices.PtzDevices.getNode(PtzDevices.java:99) [239:org.openhab.binding.ipcamera:2.3.0.201805130058]
	at de.onvif.soap.devices.PtzDevices.absoluteMove(PtzDevices.java:172) [239:org.openhab.binding.ipcamera:2.3.0.201805130058]
	at org.openhab.binding.ipcamera.handler.IpCameraHandler.handleCommand(IpCameraHandler.java:763) [239:org.openhab.binding.ipcamera:2.3.0.201805130058]
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at com.sun.proxy.$Proxy129.handleCommand(Unknown Source) [239:org.openhab.binding.ipcamera:2.3.0.201805130058]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by Skinah** [comment]
Lets work on getting the camera ONLINE first then look at PTZ issues. Please enable the debug output in the logs for this binding and then post the log output when the camera is making the connection. It will list detailed info on PTZ  and what the camera supports at the very end of connecting. The log should shows something helpful.

The log you posted has suggested 2 things is happening.

1.The camera is replying with NULL when a response is expected.
2. Profile 1 is not valid. Try selecting the ONVIF media profile to use '0' and see if that gives different results.

**Comment by brootes** [comment]
Here is what I found trying both media profiles. 
ONVIF_MEDIA_PROFILE=1
After a Reboot

2018-05-18 15:10:00.057 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP empty
2018-05-18 15:10:00.080 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888
2018-05-18 15:10:12.933 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.
2018-05-18 15:10:12.991 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0008: Bad Response; null
Logging stopped here 

After saving the ipcamera.things file.
2018-05-18 15:13:35.417 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Camera dispose called, about to remove/change or fix a Cameras connection or settings.
2018-05-18 15:13:35.422 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP xxx.xxx.xxx.xxx
2018-05-18 15:13:35.430 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888
2018-05-18 15:13:38.617 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.
2018-05-18 15:13:42.209 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the snapshot URL for the selected Media Profile.
2018-05-18 15:13:44.893 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to fetch some information about the Media Profiles from the camera
2018-05-18 15:13:44.896 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 0 details reported by camera at IP:xxx.xxx.xxx.xxx *********************
2018-05-18 15:13:44.897 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 is named:videoencoder_name0
2018-05-18 15:13:44.899 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video encoder	:H_264
2018-05-18 15:13:44.901 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video quality	:3.0
2018-05-18 15:13:44.903 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video resoltion	:1280 x 720
2018-05-18 15:13:44.905 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video bitrate	:512
2018-05-18 15:13:44.907 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 1 details reported by camera at IP:xxx.xxx.xxx.xxx *********************
2018-05-18 15:13:44.909 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Camera will use this Media Profile unless you change it in the binding by pressing on the pencil icon in PaperUI.
2018-05-18 15:13:44.911 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 is named:videoencoder_name1
2018-05-18 15:13:44.912 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video encoder	:H_264
2018-05-18 15:13:44.914 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video quality	:3.0
2018-05-18 15:13:44.916 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video resoltion	:640 x 360
2018-05-18 15:13:44.917 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video bitrate	:512
2018-05-18 15:13:44.919 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to interrogate the camera to see if it supports PTZ.
2018-05-18 15:14:08.172 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0008: Bad Response; null
Logging stopped here 

ONVIF_MEDIA_PROFILE=0
After a reboot
2018-05-18 15:21:10.612 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP empty
2018-05-18 15:21:10.624 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888
2018-05-18 15:21:23.938 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.
2018-05-18 15:21:28.006 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the snapshot URL for the selected Media Profile.
2018-05-18 15:21:28.193 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0008: Bad Response; null
2018-05-18 15:21:28.200 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - The camera connection had a SOAP error, this may indicate your camera does not fully ONVIF or is an older version. Not to worry, we will still try and connect. Camera at IP:xxx.xxx.xxx.xxx, fault was com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (-1null
2018-05-18 15:21:28.208 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera gave a SOAP exception, try over-riding the Snapshot URL auto detection.
Logging stopped here 

After saving the ipcamera.things file.
2018-05-18 15:21:10.612 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP empty
2018-05-18 15:21:10.624 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888
2018-05-18 15:21:23.938 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.
2018-05-18 15:21:28.006 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the snapshot URL for the selected Media Profile.
2018-05-18 15:21:28.193 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0008: Bad Response; null
2018-05-18 15:21:28.200 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - The camera connection had a SOAP error, this may indicate your camera does not fully ONVIF or is an older version. Not to worry, we will still try and connect. Camera at IP:xxx.xxx.xxx.xxx, fault was com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (-1null
2018-05-18 15:21:28.208 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera gave a SOAP exception, try over-riding the Snapshot URL auto detection.
Logging stopped here 

Hope this helps.

**Comment by Skinah** [comment]
Try the latest build 20-05-2018 and if that does not work, enter in the snapshot URL in the bindings parameters. It is strange as your camera sometimes replies and other times it replies with null. I would check if the camera has a newer firmware. I have added a lot more logging in this newer build.

**Comment by brootes** [comment]
Downloaded 21-05-2018 version (both media_profile 0 and 1 act about the same)
I also have tried overriding the snapshot url and get a 409 error message in PaperUI.

After camera reboot

2018-05-21 17:07:49.213 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Camera dispose called, about to remove/change or fix a Cameras connection or settings.

2018-05-21 17:07:49.217 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP xxx.xxx.xxx.xxx

2018-05-21 17:07:49.221 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888

2018-05-21 17:07:54.770 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.

2018-05-21 17:07:58.502 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the snapshot URL for the selected Media Profile.

2018-05-21 17:08:01.244 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to fetch some information about the Media Profiles from the camera

2018-05-21 17:08:01.246 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 0 details reported by camera at IP:xxx.xxx.xxx.xxx *********************

2018-05-21 17:08:01.248 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 is named:videoencoder_name0

2018-05-21 17:08:01.250 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video encoder	:H_264

2018-05-21 17:08:01.252 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video quality	:3.0

2018-05-21 17:08:01.253 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video resoltion	:1280 x 720

2018-05-21 17:08:01.255 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video bitrate	:512

2018-05-21 17:08:01.257 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 1 details reported by camera at IP:xxx.xxx.xxx.xxx *********************

2018-05-21 17:08:01.259 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Camera will use this Media Profile unless you change it in the binding by pressing on the pencil icon in PaperUI.

2018-05-21 17:08:01.260 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 is named:videoencoder_name1

2018-05-21 17:08:01.262 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video encoder	:H_264

2018-05-21 17:08:01.264 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video quality	:3.0

2018-05-21 17:08:01.266 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video resoltion	:640 x 360

2018-05-21 17:08:01.268 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video bitrate	:512

2018-05-21 17:08:01.270 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to interrogate the camera to see if it supports PTZ.

2018-05-21 17:08:01.307 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed


After saving ipcamera.thing file

Camera dispose called, about to remove/change or fix a Cameras connection or settings.

2018-05-21 17:09:17.219 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP xxx.xxx.xxx.xxx

2018-05-21 17:09:17.226 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888

2018-05-21 17:09:17.280 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Camera dispose called, about to remove/change or fix a Cameras connection or settings.

2018-05-21 17:09:17.282 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP xxx.xxx.xxx.xxx

2018-05-21 17:09:20.016 [ERROR] [sun.xml.internal.messaging.saaj.soap] - SAAJ0601.util.newSAXParser.exception

2018-05-21 17:09:20.018 [ERROR] [ml.internal.messaging.saaj.soap.impl] - SAAJ0250: Cannot extract Document from body

2018-05-21 17:09:20.021 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - The camera connection had a SOAP error, this may indicate your camera does not fully ONVIF or is an older version. Not to worry, we will still try and connect. Camera at IP:xxx.xxx.xxx.xxx, fault was javax.xml.soap.SOAPException: Cannot extract Document from body

2018-05-21 17:09:20.027 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera failed to report a valid Snaphot URL, try over-riding the Snapshot URL auto detection by entering a known URL.

2018-05-21 17:09:20.028 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888

2018-05-21 17:09:22.544 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.

2018-05-21 17:09:22.574 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed

2018-05-21 17:09:22.594 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera replied with NULL when trying to get a list of the media profiles

2018-05-21 17:09:22.597 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - NPE occured when trying to connect to the camera with ONVIF

2018-05-21 17:09:22.603 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera failed to report a valid Snaphot URL, try over-riding the Snapshot URL auto detection by entering a known URL.

**Comment by brootes** [comment]
I thought maybe an example of one time it came online might help. It is still inconsistent but does work at times.  Thank for you creating and working on the binding. 
verson - ipcamera23-05-2018
thing file contains - **Thing ipcamera:FOSCAM:001 [ IPADDRESS="xxx.xxx.xxx.xxx", PASSWORD="password",USERNAME="username", ONVIF_MEDIA_PROFILE=0 ]**

2018-05-23 20:17:23.085 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Camera dispose called, about to remove/change a Cameras settings.

2018-05-23 20:17:23.087 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Getting configuration to initialize a new IP Camera at IP xxx.xxx.xxx.xxx

2018-05-23 20:17:23.090 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:xxx.xxx.xxx.xxx:888

2018-05-23 20:17:26.596 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the number of Media Profile this camera supports.

2018-05-23 20:17:29.768 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.

2018-05-23 20:17:29.770 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching a Token for the selected Media Profile.

2018-05-23 20:17:29.772 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Auto fetching the snapshot URL for the selected Media Profile.

2018-05-23 20:17:32.453 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - About to fetch some information about the Media Profiles from the camera

2018-05-23 20:17:32.456 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 0 details reported by camera at IP:xxx.xxx.xxx.xxx *********************

2018-05-23 20:17:32.458 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Camera will use this Media Profile unless you change it in the binding by pressing on the pencil icon in PaperUI.

2018-05-23 20:17:32.460 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 is named:videoencoder_name0

2018-05-23 20:17:32.461 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video encoder	:H_264

2018-05-23 20:17:32.463 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video quality	:3.0

2018-05-23 20:17:32.465 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video resoltion	:1280 x 720

2018-05-23 20:17:32.467 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 0 uses video bitrate	:512

2018-05-23 20:17:32.469 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - ********************* Media Profile 1 details reported by camera at IP:xxx.xxx.xxx.xxx *********************

2018-05-23 20:17:32.471 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 is named:videoencoder_name1

2018-05-23 20:17:32.473 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video encoder	:H_264

2018-05-23 20:17:32.475 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video quality	:3.0

2018-05-23 20:17:32.477 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video resoltion	:640 x 360

2018-05-23 20:17:32.478 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Media Profile 1 uses video bitrate	:512

2018-05-23 20:17:32.480 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to interrogate the camera to see if it supports PTZ.

2018-05-23 20:17:35.582 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed

2018-05-23 20:17:35.603 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Camera is reporting that it does NOT support Absolute PTZ controls via ONVIF

2018-05-23 20:17:35.605 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Finished with PTZ, now fetching the Video URL's the camera supports.

2018-05-23 20:17:37.940 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed

2018-05-23 20:17:37.945 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - The camera connection had a SOAP error, this may indicate your camera does not fully support ONVIF, check for an updated firmware for your camera. Not to worry, we will still try and connect. Camera at IP:xxx.xxx.xxx.xxx, fault was com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed

2018-05-23 20:17:38.001 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Trying to connect with new request for camera at IP:xxx.xxx.xxx.xxx

2018-05-23 20:17:38.586 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - + The request is going to be GET:/cgi-bin/CGIProxy.fcgi?usr=tester&pwd=mytest123&cmd=snapPicture2:

2018-05-23 20:17:39.151 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)

HTTP/1.1 200 OK

Content-type: image/jpeg

Content-Length: 32068

Connection: close

**Comment by Skinah** [comment]
If it connects does the picture work reliably? ie is it only caused with the ONVIF code, or is it also with my http coding?
I am also wondering if this could be a faulty cat5 cable? maybe look at your cabling as I have never had issues and a number of others are also reporting the ONVIF to work without the issue you are seeing.

Another way to handle this would be to deliberately give the wrong ONVIF port and use the URL override. This way it fails the onvif and should still come online and give you all features except PTZ. PTZ needs the onvif to work.

**Comment by brootes** [comment]
It works well with the URL override. I will do more testing of features in the future. Thanks for all the hard work!

**Comment by Skinah** [comment]
@brootes 
The latest version of the binding now supports Onvif presets and uses a new method for PTZ moves so it is worth trying the latest version if you could not move the camera due to the NPE errors. Two different ways to move the camera so if one fails, try the other.
