### ISSUE TITLE
Throws exception all time

### ISSUE THREAD

**Issue by csaboka21** [Skinah/IpCamera#51]
Hello!

I got this exception all the time:

```
2020-02-27 19:22:47.618 [WARN ] [pcamera.internal.StreamServerHandler] - Exception caught from stream server:{}

java.lang.NoClassDefFoundError: io/netty/util/internal/ObjectPool$ObjectCreator

	at io.netty.buffer.PoolThreadCache.createSubPageCaches(PoolThreadCache.java:129) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:76) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:460) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:444) ~[bundleFile:4.1.45.Final]

	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177) ~[bundleFile:4.1.42.Final]

	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142) ~[bundleFile:4.1.42.Final]

	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:337) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) ~[bundleFile:4.1.45.Final]

	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139) ~[bundleFile:4.1.45.Final]

	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) ~[bundleFile:4.1.45.Final]

	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147) [bundleFile:4.1.45.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [bundleFile:4.1.45.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [bundleFile:4.1.45.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [bundleFile:4.1.45.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [bundleFile:4.1.45.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [bundleFile:4.1.42.Final]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.42.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.42.Final]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.ObjectPool$ObjectCreator cannot be found by io.netty.buffer_4.1.45.Final

	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi-3.12.100.jar:?]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]

	... 20 more
```

I have copied all file from the zip to the addons folder!

What am I doing wrong?

**Comment by Skinah** [comment]
reboot the Openhab server a few times as this can happen when a binding is added to the addons folder and the cache is not generated. Reboot 2-3 times and see if it is then fixed.

**Comment by Skinah** [comment]
Closing as its 4 weeks and no reply, feel free to open again if it is still an issue after multiple reboots.
