### ISSUE TITLE
Netty Warnings in openhab.log

### ISSUE THREAD

**Issue by rsterz** [Skinah/IpCamera#7]
I use the INSTAR 9008 FullHD with this binding (snapshot 30-05-18). With my configuration (see below) I can view the image of my cam and activate/deactivate the motion alert. Unfortunately when polling the image every 5 seconds I receive this warning in my openhab.log. Nevertheless the image is received by Openhab (2.3.0) but I am flooded by warnings.

`2018-05-30 21:53:48.946 [WARN ] [netty.channel.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
        at org.openhab.binding.ipcamera.handler.IpCameraHandler$InstarHandler.channelRead(IpCameraHandler.java:576) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at org.openhab.binding.ipcamera.handler.IpCameraHandler$CommonCameraHandler.channelRead(IpCameraHandler.java:366) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at org.openhab.binding.ipcamera.internal.MyNettyAuthHandler.channelRead(MyNettyAuthHandler.java:193) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [275:org.openhab.binding.ipcamera:2.3.0.201805300948]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`

I had to overwrite the image url as it was not recognized correctly. This is my thing configuration:
`Thing ipcamera:INSTAR:kamera [IPADDRESS="192.168.178.11", USERNAME="user", PASSWORD="password", SNAPSHOT_URL_OVERIDE="http://user:password@192.168.178.11:80/tmpfs/auto.jpg"]`

Thank you for your active development. I am happy to support by testing if that helps to provide support for the 9008.

BR
Rene

**Comment by rsterz** [comment]
One additional comment from openhab.log - during startup of the binding I receive the following error:
`2018-05-30 22:14:13.802 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:192.168.178.11:8080
2018-05-30 22:14:20.043 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching the number of Media Profile this camera supports.
2018-05-30 22:14:22.472 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Checking the selected Media Profile is a valid number.
2018-05-30 22:14:22.474 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Fetching a Token for the selected Media Profile.
2018-05-30 22:14:22.476 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to interrogate the camera to see if it supports PTZ.
2018-05-30 22:14:45.423 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Camera is reporting it supports PTZ controls via ONVIF
2018-05-30 22:14:48.512 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - Camera replied with null when asked what its position was, going to fake the position so PTZ still works.
2018-05-30 22:14:48.515 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - Finished with PTZ, now fetching the Video URL's the camera supports.
2018-05-30 22:14:53.557 [ERROR] [ing.saaj.soap.ver1_2.SOAPPart1_2Impl] - SAAJ0415: InputStream stellt keine gültige SOAP 1.2-Nachricht dar
`

The last line means "InputStream doesn't represent a valid SOAP 1.2 message"

**Comment by Skinah** [comment]
Found and fixed a bug. New build should be available shortly.

**Comment by rsterz** [comment]
Thank you for the quick fix. It works without warnings now. The SOAP error is still appearing during startup but I don't care about that. If you are fine with that feel free to close this issue 👍
